@startuml

start

:Usuário abre o aplicativo;

if (Possui conta?) then (não)

  :Tela de cadastro;
  :Inserir nome, email e senha;
  :Criar conta;

else (sim)

  :Tela de login;
  :Inserir email e senha;

  if (Login válido?) then (sim)
    :Acessar aplicativo;

  else (não)
    :Exibir erro de login;

    if (Esqueceu a senha?) then (sim)
      :Inserir email;
      :Enviar email de recuperação;
      :Redefinir senha;
      :Voltar ao login;
    else (não)
      :Tentar login novamente;
    endif

  endif

endif


:Menu principal;

if (Adicionar carro?) then (sim)

  :Abrir galeria;
  :Filtrar fotos da câmera;
  :Usuário seleciona foto;

  :Enviar imagem para reconhecimento;

  :Sistema identifica veículo;
  :O veiculo é adicionado;

  

@enduml